### ISSUE TITLE
plugin doesn't seem to be functioning

### ISSUE THREAD

**Issue by williamkray** [ajkessel/reacjibot#2]
i have been struggling to get this plugin to work. one possible factor may be that i'm attempting to use it in an encrypted room, but the other seems to be that it doesn't actually parse what unicode emoji is supposed to match.

i have the following setting in my config:

```
mapping:
    📣: !myroomid:myserver.tld
```

however, when i add a 📣 reaction to a message, the bot doesn't seem to identify it as anything it's meant to repost elsewhere.

if i react to it with the train emoji given in the original example config, however, it does... but it's throwing the following error:

```
[10:05:25](file:////usr/lib/python3.11/site-packages/mautrix/client/syncer.py:238)ERROR[client/@clorg:jobmachine.org](https://maubot.dev.jobmachine.org/#/client/@clorg:jobmachine.org)Failed to run handler
[10:05:25](file:////usr/lib/python3.11/site-packages/mautrix/client/syncer.py:238)ERROR[client/@clorg:jobmachine.org](https://maubot.dev.jobmachine.org/#/client/@clorg:jobmachine.org)Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/mautrix/client/syncer.py", line 236, in _catch_errors
    await handler(data)
  File "/opt/maubot/maubot/handlers/command.py", line 480, in replacement
    await func(self, evt, val)
  File "/data/plugins/org.rosi-kessel.reacjibot-v0.4.1.mbp/reacjibot/bot.py", line 51, in generic_react
    await self.client.send_markdown(target_id,message)
  File "/opt/maubot/maubot/matrix.py", line 271, in send_markdown
    return await self.send_message(room_id, content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/client/encryption_manager.py", line 157, in send_message_event
    await self.get_state_event(room_id, EventType.ROOM_ENCRYPTION)
  File "/usr/lib/python3.11/site-packages/mautrix/client/store_updater.py", line 201, in get_state_event
    event = await super().get_state_event(room_id, event_type, state_key)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/client/api/events.py", line 192, in get_state_event
    content = await self.api.request(
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 415, in request
    resp_data, resp = await self._send(
                      ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/mautrix/api.py", line 265, in _send
    raise make_request_error(
mautrix.errors.request.MUnrecognized: Unrecognized request
```

so this seems to indicate that the emoji to react to is not being parsed from the actual config of the instance (i don't use the train emoji), and that the message content is not being captured if the message is in an encrypted room. i question the emoji mapping logic being used here most.

i think it's reasonable to say that the plugin doesn't support encrypted rooms for security (in theory, you shouldn't have an encrypted room and then have the ability to post the content from it to another, unencrypted room). however this should be called out in the readme, probably.

ultimately, i haven't spent a ton of time testing every version of possible scenarios, but none of the ones that i have tested actually achieve the goal of this plugin.

**Comment by ajkessel** [comment]
I've only used it in encrypted rooms, so that shouldn't be the issue. I'll take a look at your scenario and see if I can replicate.

**Comment by ajkessel** [comment]
Seems like the issue is you need to put quotes around the room name if you are going to do a full-qualified room name rather than a local alias. I tried your example (with the megaphone) and fully defining the room (with !room_id:server.tld , rather than an alias) and it didn't work without the quotes. 

There also may be a bug that it is not re-processing the configuration file when you save it. I'm looking at that now, but in the meantime let me know if quoting the room name fixes it for you. I'll also update the documentation.

**Comment by ajkessel** [comment]
OK, I've fixed the documentation to indicate quotes are needed for full room names, and also tweaked the code so it properly reloads when you change the config ([1bccf0adc5cc82c51661df2f308e6626392fbe7f](https://github.com/ajkessel/reacjibot/commit/1bccf0adc5cc82c51661df2f308e6626392fbe7f)). I think this should fix your issues. If it does, please close this issue.

**Comment by ajkessel** [comment]
OK, I've fixed the documentation to indicate quotes are needed for full room names, and also tweaked the code so it properly reloads when you change the config ([1bccf0adc5cc82c51661df2f308e6626392fbe7f](https://github.com/ajkessel/reacjibot/commit/1bccf0adc5cc82c51661df2f308e6626392fbe7f)). I think this should fix your issues. If it does, please close this issue.

**Comment by ajkessel** [comment]
And @williamkray, thanks for your patience, this is my first foray into this sort of thing.

**Comment by williamkray** [comment]
aha, updated and put quotes and it seems to be working as expected... new discovery:

seems like the message is prefixed by the name of the person who added the emoji react, but i would expect it to have the name of the person who sent the original message, no? is that crazy?

**Comment by williamkray** [comment]
i'll close this though since it's working :+1:

**Comment by williamkray** [comment]
it also appears to append the echoed message with the reactji used to trigger the echo, so... that seems unintended?

**Comment by ajkessel** [comment]
> it also appears to append the echoed message with the reactji used to trigger the echo, so... that seems unintended?

That is intended--the appended-emoji is a hyperlink back to the original message. I guess that's not obvious from looking at it but let me know if it isn't working as intended on your end. 

This could be perhaps best addressed by my plan to allow templating the cross-post so you can specify what you want there.

**Comment by ajkessel** [comment]
> seems like the message is prefixed by the name of the person who added the emoji react, but i would expect it to have the name of the person who sent the original message, no? is that crazy?

Good question, I was mulling that over myself earlier today. The behavior could be to identify original poster, the cross-poster emoji-adder, or both. This again could be fixed via template options (or other configurability) but maybe it does make more sense in the short term to have the name be the original poster rather than the cross poster. I've changed that behavior in [https://github.com/ajkessel/reacjibot/commit/072384ac2c6db7f80e98f2b91ef6a17a6cf45a1f](072384ac2c6db7f80e98f2b91ef6a17a6cf45a1f) and am open to suggestions for the best way to show sender and cross-poster in future releases.

**Comment by williamkray** [comment]
ahhh, i wasn't getting that the emoji was a hyperlink... it does indeed function properly. templating the format of the echoed message would be very handy, but could get complicated. i'll let you play with that as needed for a future release :stuck_out_tongue_winking_eye:
